version: "3.8"
services:
    web:
      image: httpd
      ports:
         - 80:80
    app:
      image: ibmcom/websphere-traditional
    mq:
      image: ibmcom/mq
    db:
      image: ibmcom/db2
      environment:
              - DB2INST=db2inst1
networks:
     default:
         aliases:
             webservice 
      
